text.code.0=FFAA00
text.code.1=FFAA00
text.code.2=FFAA00
text.code.3=FFAA00
text.code.4=FFAA00
text.code.5=FFAA00
text.code.6=FFAA00
text.code.7=FFAA00
text.code.8=FFAA00
text.code.9=FFAA00
text.code.10=FFAA00
text.code.11=FFAA00
text.code.12=FFAA00
text.code.13=FFAA00
text.code.14=FFAA00
text.code.15=FFAA00
text.code.16=FFAA00
text.code.17=FFAA00
text.code.18=FFAA00
text.code.19=FFAA00
text.code.20=FFAA00
text.code.21=FFAA00
text.code.22=FFAA00
text.code.23=FFAA00
text.code.24=FFAA00
text.code.25=FFAA00
text.code.26=FFAA00
text.code.27=FFAA00
text.code.28=FFAA00
text.code.29=FFAA00
text.code.30=FFAA00
text.code.31=FFAA00